### ISSUE TITLE
Funktions not available (GrapheneOS +Aurora-Store)

### ISSUE THREAD

**Issue by speedy-10** [pastillilabs/packages#5]
Hi, I've a fresh installed Pixel 6a with https://grapheneos.org/ and installed Aurora-store.
(Android 14, Kernel.5.10.199)
I'd like to use situations to disable WiFi, but I can't add Funktions (like I'm useg to from SailfishOS).
How could I add more functions?
Regards
![signal-2023-11-18-184713](https://github.com/pastillilabs/packages/assets/20227451/743d749f-3f5d-4eab-bace-9cf443115290)

**Comment by hhaveri** [comment]
Hi,

Many features of Situations on Android are paid features and thus the system is dependent on Google Play. Unfortunately we don't have capacity to support other stores at the moment.

Another problem is that Google has removed the possibility from 3rd party apps to toggle WiFi on/off (in Android 9). The same happened quite recently also with Bluetooth (Android 13). On a rooted phone these functions should still work - although they are largely untested.

So not much can be done about these, I'm afraid :(

Br,
  Heikki
